# Calculating a d' for a single session

In [36]:
import json
import pandas as pd
import numpy as np

from scipy.stats import norm

## Read in a go/nogo session

In [3]:
session_path = "./test_data/example-gonogo-leverpush.json"
with open(session_path, "r") as fp:
    session_data = json.load(fp)

session_data

{'animal_id': 'MM229',
 'experiment': '109hrb21d',
 'duration': 30.0,
 'protocol': 'gonogo',
 'spec': {'response_device': 'leverpush',
  'response_address': '/dev/ttyUSB1',
  'reward_profile': 'waterreward',
  'reward_address': '/dev/ttyUSB0',
  'iti': '5000',
  'stimulus_duration': '4000',
  'corrections_enabled': 'true',
  'target': 'movinggrating',
  't_period': '30',
  't_contrast': '1.0',
  't_freq': '1.0',
  'distractor': 'isoluminantgray'},
 'complete': True,
 'timestamp': '2022-03-09T12:04:03.108928',
 'notes': '',
 'device': 'meso-2',
 'trials': [{'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:04:07.593607',
   'correction': False,
   'response_time': -1},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:04:22.174603',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:04:18.100767',
   'correction': False,
   'response_time': 4.072411060333252},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:04:28.305482',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:04:22.176107',
   'correction': False,
   'response_time': 1.128455638885498},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:04:29.809401',
   'correction': False,
   'response_time': -1},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:04:46.990000',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:04:40.315873',
   'correction': False,
   'response_time': 1.670673131942749},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:04:54.249935',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:04:48.494275',
   'correction': False,
   'response_time': 0.7522234916687012},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:04:58.588057',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:04:54.251548',
   'correction': True,
   'response_time': 4.335704565048218},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:04.311243',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:04:58.590173',
   'correction': True,
   'response_time': 0.7189033031463623},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:09.896238',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:04.312841',
   'correction': True,
   'response_time': 0.5815799236297607},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:12.781422',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:09.898236',
   'correction': True,
   'response_time': 2.8821327686309814},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:20.423976',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:12.783346',
   'correction': True,
   'response_time': 2.6385655403137207},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:26.451898',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:20.425591',
   'correction': True,
   'response_time': 1.023176670074463},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:32.547632',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:26.453505',
   'correction': True,
   'response_time': 1.0914087295532227},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:38.460012',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:32.549304',
   'correction': True,
   'response_time': 0.9076066017150879},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:44.052376',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:38.462042',
   'correction': True,
   'response_time': 0.5879597663879395},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:48.224129',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:44.054314',
   'correction': True,
   'response_time': 4.168878555297852},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:55.211460',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:48.225737',
   'correction': True,
   'response_time': 1.9838838577270508},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:05:59.345341',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:05:55.213395',
   'correction': True,
   'response_time': 4.130924463272095},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:05:59.346905',
   'correction': True,
   'response_time': -1},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:12.228297',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:09.852276',
   'correction': False,
   'response_time': 2.3747329711914062},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:13.474516',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:12.229916',
   'correction': False,
   'response_time': 1.2436370849609375},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:22.096334',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:13.476070',
   'correction': False,
   'response_time': 3.618813991546631},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:25.020616',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:23.600731',
   'correction': False,
   'response_time': 1.417907476425171},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:27.328321',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:25.022112',
   'correction': False,
   'response_time': 2.305368185043335},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:28.463599',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:27.329831',
   'correction': False,
   'response_time': 1.1328802108764648},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:29.670923',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:28.465094',
   'correction': False,
   'response_time': 1.2049245834350586},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:38.286164',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:29.672327',
   'correction': False,
   'response_time': 3.6107337474823},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:44.333870',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:38.288012',
   'correction': True,
   'response_time': 1.0434894561767578},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:06:49.993457',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:06:44.335644',
   'correction': True,
   'response_time': 0.6549959182739258},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:06:49.995252',
   'correction': True,
   'response_time': -1},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:07:05.389140',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:00.500451',
   'correction': False,
   'response_time': 4.886905193328857},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:07:10.851744',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:05.390884',
   'correction': False,
   'response_time': 0.4594407081604004},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:07:17.620981',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:12.355668',
   'correction': False,
   'response_time': 0.2632710933685303},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:07:23.317530',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:19.125095',
   'correction': False,
   'response_time': 4.190792798995972},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:07:29.604497',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:23.319294',
   'correction': False,
   'response_time': 1.2839653491973877},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:07:36.987203',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:31.108939',
   'correction': False,
   'response_time': 0.8774118423461914},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:07:43.207672',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:38.493088',
   'correction': False,
   'response_time': 4.713680982589722},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:07:43.209047',
   'correction': False,
   'response_time': -1},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:07:59.213148',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:53.714519',
   'correction': False,
   'response_time': 0.4971010684967041},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:08:04.782887',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:07:59.214535',
   'correction': True,
   'response_time': 0.5659911632537842},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:08:08.753776',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:08:04.784584',
   'correction': True,
   'response_time': 3.968205213546753},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:08:08.755505',
   'correction': True,
   'response_time': -1},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:08:25.107594',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:08:19.260744',
   'correction': False,
   'response_time': 0.8459694385528564},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:08:32.455658',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:08:26.613059',
   'correction': False,
   'response_time': 0.8411245346069336},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:08:36.201889',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:08:33.959956',
   'correction': False,
   'response_time': 2.240708112716675},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:08:36.203231',
   'correction': False,
   'response_time': -1},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:08:52.162011',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:08:46.709147',
   'correction': False,
   'response_time': 0.4502274990081787},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:08:58.192669',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:08:53.666323',
   'correction': False,
   'response_time': 4.5249738693237305},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:05.107361',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:08:58.194037',
   'correction': False,
   'response_time': 1.9102110862731934},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:09.890886',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:05.109067',
   'correction': True,
   'response_time': 4.780845403671265},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:15.426160',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:09.892280',
   'correction': True,
   'response_time': 0.5310475826263428},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:19.229491',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:15.427599',
   'correction': True,
   'response_time': 3.8010411262512207},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:24.202969',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:19.231169',
   'correction': True,
   'response_time': 4.9708380699157715},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:27.672480',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:24.204653',
   'correction': True,
   'response_time': 3.4667932987213135},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:32.647224',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:27.673773',
   'correction': True,
   'response_time': 4.9726316928863525},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:33.853206',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:32.648622',
   'correction': True,
   'response_time': 1.2038044929504395},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:36.098640',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:33.854897',
   'correction': True,
   'response_time': 2.2427523136138916},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:09:36.100351',
   'correction': True,
   'response_time': -1},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:09:52.315407',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:46.605753',
   'correction': False,
   'response_time': 0.7076911926269531},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:10:00.320211',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:09:52.316882',
   'correction': True,
   'response_time': 3.0002448558807373},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:10:00.322004',
   'correction': True,
   'response_time': -1},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:10:16.571048',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:10:10.828621',
   'correction': False,
   'response_time': 0.7406089305877686},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:10:19.467641',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:10:18.075002',
   'correction': False,
   'response_time': 1.391491413116455},
  {'outcome': 'incorrect',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:10:24.964324',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:10:19.469598',
   'correction': False,
   'response_time': 0.4915797710418701},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': None,
   'timestamp': '2022-03-09T12:10:24.966752',
   'correction': True,
   'response_time': -1},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:10:41.102151',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:10:35.472518',
   'correction': False,
   'response_time': 0.6276063919067383},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:10:46.364535',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:10:42.604712',
   'correction': False,
   'response_time': 3.7589306831359863},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:10:51.304287',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:10:46.365747',
   'correction': False,
   'response_time': 4.937792062759399},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:10:56.815072',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:10:51.305763',
   'correction': False,
   'response_time': 0.5083510875701904},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:11:01.115637',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:10:58.319045',
   'correction': False,
   'response_time': 2.794562816619873},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:11:03.822301',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:11:01.117622',
   'correction': False,
   'response_time': 2.703796148300171},
  {'outcome': 'precued',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:11:08.221073',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:11:03.823953',
   'correction': False,
   'response_time': 4.39621901512146},
  {'outcome': 'correct',
   'iti': 5.0,
   'response': {'timestamp': '2022-03-09T12:11:13.649075',
    'pos_x': 400.0,
    'pos_y': 240.0,
    'dist_x': 0,
    'dist_y': 0},
   'timestamp': '2022-03-09T12:11:08.222720',

In [9]:
df = pd.DataFrame(session_data["trials"])
df

,outcome,iti,response,timestamp,correction,response_time
0,correct,5.0,None,2022-03-09T12:04:07.593607,False,-1.000000
1,precued,5.0,"{'timestamp': '2022-03-09T12:04:22.174603', 'p...",2022-03-09T12:04:18.100767,False,4.072411
2,correct,5.0,"{'timestamp': '2022-03-09T12:04:28.305482', 'p...",2022-03-09T12:04:22.176107,False,1.128456
3,correct,5.0,None,2022-03-09T12:04:29.809401,False,-1.000000
4,correct,5.0,"{'timestamp': '2022-03-09T12:04:46.990000', 'p...",2022-03-09T12:04:40.315873,False,1.670673
...,...,...,...,...,...,...
300,incorrect,5.0,"{'timestamp': '2022-03-09T12:33:37.164753', 'p...",2022-03-09T12:33:28.955942,True,3.207015
301,incorrect,5.0,"{'timestamp': '2022-03-09T12:33:44.960095', 'p...",2022-03-09T12:33:37.166389,True,2.791260
302,precued,5.0,"{'timestamp': '2022-03-09T12:33:49.434693', 'p...",2022-03-09T12:33:44.961767,True,4.472022
303,correct,5.0,None,2022-03-09T12:33:49.436672,True,-1.000000
304,incorrect,5.0,"{'timestamp': '2022-03-09T12:34:05.771623', 'p...",2022-03-09T12:33:59.940888,False,0.828844

In [10]:
df[df.outcome == "correct"]

,outcome,iti,response,timestamp,correction,response_time
0,correct,5.0,None,2022-03-09T12:04:07.593607,False,-1.000000
2,correct,5.0,"{'timestamp': '2022-03-09T12:04:28.305482', 'p...",2022-03-09T12:04:22.176107,False,1.128456
3,correct,5.0,None,2022-03-09T12:04:29.809401,False,-1.000000
4,correct,5.0,"{'timestamp': '2022-03-09T12:04:46.990000', 'p...",2022-03-09T12:04:40.315873,False,1.670673
18,correct,5.0,None,2022-03-09T12:05:59.346905,True,-1.000000
...,...,...,...,...,...,...
291,correct,5.0,"{'timestamp': '2022-03-09T12:32:49.893590', 'p...",2022-03-09T12:32:44.376805,False,0.515259
292,correct,5.0,"{'timestamp': '2022-03-09T12:32:57.060164', 'p...",2022-03-09T12:32:51.397986,False,0.658831
296,correct,5.0,"{'timestamp': '2022-03-09T12:33:12.462742', 'p...",2022-03-09T12:33:06.548516,False,0.911193
297,correct,5.0,"{'timestamp': '2022-03-09T12:33:20.414523', 'p...",2022-03-09T12:33:13.966443,False,1.445968
303,correct,5.0,None,2022-03-09T12:33:49.436672,True,-1.000000

## Calculate a session d'

In [ ]:
# hit rate

hits = len(
    df[(df.outcome == "correct") & (df.response.notnull()) & (df.correction == False)]
)

misses = len(
    df[(df.outcome == "incorrect") & (df.response.isnull()) & (df.correction == False)]
)

hit_rate = (hits + 0.5) / (hits + misses + 1.0)
print(hit_rate)

0.99

In [ ]:
# FA rate

false_alarms = len(
    df[(df.outcome == "incorrect") & (df.response.notnull()) & (df.correction == False)]
)

correct_reject = len(
    df[(df.outcome == "correct") & (df.response.isnull()) & (df.correction == False)]
)

fa_rate = (false_alarms + 0.5) / (false_alarms + correct_reject + 1)
print(fa_rate)

0.7641509433962265

In [ ]:
# calculate d'

d_prime = norm.ppf(hit_rate) - norm.ppf(fa_rate)
print(d_prime)

1.606629016515605